import { MapSymbol as MS } from '@/models/MapSymbol'

const grid = [
  [MS.EMPTY, MS.EMPTY, MS.EMPTY, MS.EMPTY, MS.EMPTY, MS.EMPTY, MS.EMPTY, MS.EMPTY],
  [MS.EMPTY, MS.ROCK, MS.ROCK, MS.EMPTY, MS.EMPTY, MS.ROCK, MS.ROCK, MS.EMPTY],
  [MS.EMPTY, MS.ROCK, MS.ROCK, MS.EMPTY, MS.EMPTY, MS.EMPTY, MS.ROCK, MS.EMPTY],
  [MS.EMPTY, MS.ROCK, MS.EMPTY, MS.EMPTY, MS.EMPTY, MS.ROCK, MS.ROCK, MS.EMPTY],
  [MS.EMPTY, MS.EMPTY, MS.EMPTY, MS.EMPTY, MS.EMPTY, MS.EMPTY, MS.EMPTY, MS.EMPTY],
  [MS.EMPTY, MS.ROCK, MS.EMPTY, MS.EMPTY, MS.EMPTY, MS.ROCK, MS.ROCK, MS.EMPTY],
  [MS.EMPTY, MS.ROCK, MS.ROCK, MS.EMPTY, MS.ROCK, MS.ROCK, MS.ROCK, MS.EMPTY],
  [MS.EMPTY, MS.EMPTY, MS.EMPTY, MS.EMPTY, MS.EMPTY, MS.EMPTY, MS.EMPTY, MS.EMPTY]
]

export default grid
